### ISSUE TITLE
Update instructions to run using the correct image name

### ISSUE THREAD

**Issue by Bnjoroge1** [randalburns/pcds.2024#1]
After following the instructions to set up docker(on my Mac), seems like the second instruction to run the image is using the wrong image name, 
docker run -i -t --mount type=bind,source="/$(pwd)"/../ebook,target=/home/jupyteruser/ebook -p8888:8888 ppenv

It should be pp.ebook:latest not ppenv.

**Comment by randalburns** [comment]
Thanks. You're on it. Cleaned this up with latest commit and removed `--allow-root` from jupyter line.
